### ISSUE TITLE
v3.21.903: Electron: A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by aleksey-hoffman** [xxoo/node-fswin#30]
Hi, 
I upgraded `fswin` to version  `3.21.903`  in my Electron. And I got an error in production build, pointing to `fswin`:

```
A dynamic link library (DLL) initialization routine failed
```

![image](https://user-images.githubusercontent.com/84930340/132105993-91bb8f23-d758-421d-a55f-1a1d20f2376e.png)

Here's the commit: https://github.com/aleksey-hoffman/sigma-file-manager/commit/ce9a70e95236628433c35e562d311d912a875a15
See this issue for more details: https://github.com/aleksey-hoffman/sigma-file-manager/issues/139

I didn't see this error on my computer, but one of the users encountered it. I downgraded to version `3.21.107`, and according to the user, the error went away when they installed the build with the revert commit: https://github.com/aleksey-hoffman/sigma-file-manager/commit/3b4a4f58afd7a09d23fca28fdcf23305f8468331

**Comment by xxoo** [comment]
yes there is something wrong with `win_delay_load_hook.cc` i did not notice.

**Comment by xxoo** [comment]
the npm package is updated. the `win_delay_load_hook.cc` file is not included in the repo cause node-gyp will automatically add this file when building. but since 902 i switched to the nw.js version, which brings this issue. but anyway it should be fixed now

**Comment by aleksey-hoffman** [comment]
@xxoo Thank you for fixing the problem.

I found one issue with it though, after updating to `905`, it still shows version `903` when you require it:

###  package.json
```js
"fswin": "^3.21.905",
```

### console
![image](https://user-images.githubusercontent.com/61761672/132122921-22377d3a-ed68-4759-b7fb-99aee92ef89e.png)

**Comment by xxoo** [comment]
necessary changes only take place in the build environment. i don't want to update the reop just for a version number change...

**Comment by aleksey-hoffman** [comment]
@xxoo yeah that's fine, I understand. Just wanted to let you know, in case it wasn't intentional
